apiVersion: v1
kind: ServiceAccount
metadata:
  name: starwars
automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: deathstar
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    org: empire
    class: deathstar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deathstar
spec:
  replicas: 1
  selector:
    matchLabels:
      org: empire
      class: deathstar
  template:
    metadata:
      labels:
        org: empire
        class: deathstar
    spec:
      serviceAccountName: starwars
      containers:
      - name: deathstar
        image: docker.io/cilium/starwars
      # nodeName: k8s2
---
apiVersion: v1
kind: Pod
metadata:
  name: xwing
  labels:
    org: alliance
    class: xwing
spec:
  serviceAccountName: starwars
  containers:
  - name: spaceship
    image: docker.io/tgraf/netperf
  # nodeName: k8s1
